res/xml/method.xml, res/xml/qwerty.xml, srcs/juloo.keyboard2/Config.java, srcs/juloo.keyboard2/KeyModifier.java, srcs/juloo.keyboard2/KeyValue.java
This is my shot at adding Latvian specific characters (using cedille, caron (new) and macron (new) accents). Are these changes enough? I have no clue on how to build .apk for testing.
Also, I am not sure about lines like the following in `res/xml/qwerty.xml`:
```xml
<key key0="s" key1="accent_caron" key1="accent_ring" key3="ß" />
```
Will this work? Or is there another way to define multiple accents for one key? Or should I add additional accent as a new key (for example, as `key2="accent_caron"` in this example)?
=> Add keys for Latvian

res/values-es/strings.xml, res/values/strings.xml, res/xml/qwerty_es.xml, res/xml/settings.xml, srcs/juloo.common/IntSlideBarPreference.java, srcs/juloo.common/SlideBarPreference.java
First of all, thank you for creating this keyboard and thank F-Droid for listing it. I wouldn't ever have known this was even a thing otherwise.
This is a bunch of tweaks I find useful, and a fix for a minor display glitch. None of these tweaks looked major enough to warrant their own pull request, but I think all of them will be useful.
Please let me know if you want me to edit or drop some commits.
=> Miscellaneous tweaks

res/values-zh-rCN/strings.xml
Translated into Chinese-Simplified (res/value-zh-rCN).
=> Translate into Chinese-Simplified

res/xml/numeric.xml, res/xml/qwerty_es.xml, srcs/juloo.keyboard2/KeyModifier.java, srcs/juloo.keyboard2/KeyValue.java
Commits should be self-explanatory.
This is a rather small PR adding the symbols I mentioned at #108, and some extra others like `≈`, `‰`, and arrows.
I'm holding off on adding diacritics for the moment; it seems sensible to wait for feedback for some users.
Please tell me if you want me to change anything.
=> Extra characters as per #108

res/values-de/strings.xml
Translated the newly added strings (lockable modifiers, programming keyboard layout)
=> German translation update

res/values-pt/strings.xml
Updates to Brazilian Portuguese translations of values/strings.xml
=> Brazilian portuguese translations

res/values/arrays.xml, res/xml/bangla.xml, res/xml/method.xml, srcs/juloo.keyboard2/Config.java
This PR contains the Bengali keyboard layout. I hope everything is okay to merge it.
=> Bengali Keyboard Layout

res/values/arrays.xml, res/xml/hindi.xml, res/xml/method.xml, srcs/juloo.keyboard2/Config.java
This PR contains the Hindi keyboard layout. I hope everything is okay to merge it.
=> Added Hindi language layout

res/values/arrays.xml, res/xml/method.xml, res/xml/qwerty_el.xml, srcs/juloo.keyboard2/Config.java
Made it for myself, it's pretty basic, just changed what I could see real quick but it works. Also no idea how to add 'tones' (έ,ί,ό) but really for those you use word suggestions. Also for dummies like me you might want to mention in contributing readme that you need to edit Config.xml for layouts :P
Take it or leave it I don't mind.
=> Basic greek layout.

res/values-pl/strings.xml, res/values/arrays.xml, res/xml/qwerty_pl.xml, srcs/juloo.keyboard2/Config.java
because that ł under a triggered me.
Also updated translations
=> Added qwerty_pl layout

res/values-cs/strings.xml, res/values-de/strings.xml, res/values-es/strings.xml, res/values-fr/strings.xml, res/values-it/strings.xml, res/values-ko/strings.xml, res/values-lv/strings.xml, res/values-pl/strings.xml, res/values-pt/strings.xml, res/values-ru/strings.xml, res/values-tr/strings.xml, res/values-zh-rCN/strings.xml, res/values/arrays.xml, res/values/strings.xml, res/values/themes.xml, srcs/juloo.keyboard2/Config.java
problem:
solution:
problem:
solution:
=> Add theme 'ePaper'

res/values-cs/strings.xml, res/values-de/strings.xml, res/values-es/strings.xml, res/values-fr/strings.xml, res/values-it/strings.xml, res/values-ko/strings.xml, res/values-lv/strings.xml, res/values-pl/strings.xml, res/values-pt/strings.xml, res/values-ru/strings.xml, res/values-tr/strings.xml, res/values-vi/strings.xml, res/values-zh-rCN/strings.xml, res/values/arrays.xml, res/values/strings.xml, res/values/themes.xml, srcs/juloo.keyboard2/Config.java
=> Add theme "Alternative Black"

metadata/android/lv-LV/full_description.txt, metadata/android/lv-LV/short_description.txt
=> Update translation for description in Latvian

res/values-de/strings.xml
=> Update German strings.xml

srcs/juloo.keyboard2/Keyboard2.java
Set keyboard bottom gravity and adjust inputArea height so it doesn't appear on top in fullscreen.
=> Fix gravity of keyboard in full screen

res/values-pt/strings.xml
=> Update pt-br translation

res/values-pl/strings.xml
[69e0b4c](https://github.com/Julow/Unexpected-Keyboard/commit/69e0b4c2a2424b83ce0ec876938ec3e73dd5b612)
=> Updated pl (Polish) translation

res/xml/arab_pc_ir.xml
Another PR related to PR #395.
=> Change some characters' position

res/values-pt/strings.xml
=> Update translations pt-br

res/values/layouts.xml, res/xml/latn_qwerty_cz.xml
Add Czech QWERTY layout as discussed at #444
=> Add Czech QWERTY layout

res/values/layouts.xml, res/xml/armenian_ph_am.xml
Compiled and tested on an android device.
=> Add Armenian layout

res/values-lv/strings.xml
https://github.com/Julow/Unexpected-Keyboard/issues/373#issuecomment-1859258816
=> Add missing Latvian translations

res/values-tr/strings.xml
=> Update Turkish Translation

srcs/juloo.keyboard2/KeyboardData.java
Adds eight compass-point synonyms for key1 through key8
=> Compass-point synonyms for edge keys in layouts

build.gradle, gen_emoji.py, res/raw/emojis.txt, srcs/juloo.keyboard2/Emoji.java, srcs/juloo.keyboard2/EmojiGridView.java, srcs/juloo.keyboard2/EmojiGroupButtonsBar.java
Finally got a chance to take a look at updating the emoji backend, apologies for the wait!
I made what seemed to be the most necessary changes talked about in #583:
- Removing unused information (names and descriptions) from the Emoji class
- Creating a Gradle task that generates a more efficient `res/raw/emojis.txt` file from the most recent Unicode standard
- Saving recently used emoji preferences as emoji values rather than names
- Migrating old user preferences to the new system
I kept the Emoji class because it keeps EmojiGridView and EmojiGroupButtonsBar cleaner and keeps space for potential features like #173, which would require more emoji-specific functionality than is offered by KeyValue.
<br>
The code does all of the above as it is now, but as part of the update I'd like to …
=> Emoji Update

doc/Custom-layouts.md, srcs/juloo.keyboard2/Keyboard2View.java, srcs/juloo.keyboard2/KeyboardData.java, srcs/juloo.keyboard2/Pointers.java, srcs/juloo.keyboard2/Theme.java
This adds the new 'anticircle' attribute to layouts '<key>' elements that configure the key to send when doing a anti-clockwise circle gesture on it.
=> Configure anticircle gesture per-key

doc/Custom-layouts.md
=> Possible key values: Re-add text for better overview; discussed in #696

srcs/juloo.keyboard2/KeyValue.java, srcs/layouts/arab_pc_ir.xml, srcs/layouts/beng_provat.xml
Related to https://github.com/Julow/Unexpected-Keyboard/pull/709. I tryied to fix the problems.
=> Fix persian's half-space's visibility and add a 0.5 width before it's ظ

srcs/layouts/latn_qwerty_pl.xml
=> Revert "latn_qwerty_pl: Consistent placement for ó"

srcs/juloo.keyboard2/KeyValue.java, srcs/juloo.keyboard2/prefs/ExtraKeysPreference.java
and make it selectable as an extra key
=> Add new keyevent "menu"

srcs/juloo.keyboard2/KeyModifier.java
Fn modifier switches cursor_left to home key, cursor_right to end key.
=> Update KeyModifier.java, Fn for Cursor_move

srcs/layouts/arab_pc_ir.xml
=> Change the place of چ  and ژ in Persian Keyboard Layout

res/values-cs/strings.xml, res/values-de/strings.xml, res/values-es/strings.xml, res/values-fa/strings.xml, res/values-fr/strings.xml, res/values-it/strings.xml, res/values-ja/strings.xml, res/values-ko/strings.xml, res/values-lv/strings.xml, res/values-pl/strings.xml, res/values-pt/strings.xml, res/values-ro/strings.xml, res/values-ru/strings.xml, res/values-tr/strings.xml, res/values-uk/strings.xml, res/values-vi/strings.xml, res/values-zh-rCN/strings.xml, res/values/arrays.xml, res/values/strings.xml, res/values/themes.xml, srcs/juloo.keyboard2/Config.java
Hello!
I just wanted to add a [Rosé Pine](https://rosepinetheme.com/) theme.
I hope you like it!
Kind regards.
=> Rosé Pine Theme

check_layout.output, res/values/layouts.xml, srcs/layouts/arab_pc_ckb.xml, srcs/layouts/arab_pc_ckb_fa.xml
This is the two layouts I provided in issue #541
One is just the existing one, but I fixed a few problems. The other is a new one I designed.
=> New and Improved Kurdish layouts

check_layout.output, res/values/layouts.xml, srcs/layouts/georgian_mes.xml, srcs/layouts/georgian_qwerty.xml
Decided to make some layouts for Georgian, because it definitely doesn't seem like this app has any.
=> Georgian layouts added

check_layout.output, res/values/layouts.xml, srcs/layouts/latn_qwerty_ga.xml
=> Irish layout

check_layout.output, res/values/layouts.xml, srcs/layouts/latn_qwerty_haw.xml
=> Hawaiian layout

check_layout.output, res/values/layouts.xml, srcs/layouts/cyrl_jcuken_kk.xml, srcs/layouts/latn_qwerty_kk.xml
=> Kazakh Cyrillic and Latin layouts

res/values/themes.xml
Fix https://github.com/Julow/Unexpected-Keyboard/issues/797
=> Make Monet (Dark) theme darker

doc/Custom-layouts.md, srcs/juloo.keyboard2/KeyboardData.java, srcs/juloo.keyboard2/LayoutModifier.java
#890; BQN layout coming afterward as it depends on this.
=> Add embedded_number_row keyboard attribute

doc/Possible-key-values.md
Also, regarding escapes: ➊ The new syntax adds `:` and `,` as characters with special meanings and it would be nice to be able to escape them too. ➋ The section needs an Intro: What escaping is and where you can do so. Perhaps also demote the section so it's the tail end of the general syntax rules. Then the next major section starts the list of keywords previewed above.
=> Clerical edits to "Possible values.md"

srcs/layouts/latn_qwerty_us.xml
- Added info on bottom row customization. (#637)
- Added useful links.
=> Update layout customization info in srcs/layouts/latn_qwerty_us.xml

srcs/juloo.keyboard2/Config.java, srcs/juloo.keyboard2/NumberLayout.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/1030
Thanks @Nereplameri for your help debugging this.
=> Fix crash with unexpected value in NumberLayout pref

srcs/juloo.keyboard2/KeyEventHandler.java
Issue: https://github.com/Julow/Unexpected-Keyboard/issues/1032
=> Workaround Godot editor not implementing setSelection()

doc/Custom-layouts.md
the web editor has been unmaintained for some time now, so i [updated some things](https://github.com/domportera/app-unexpected-keyboard-layout-editor/blob/master/CHANGELOG) that could be nice to share 
heres the link for convenience https://domportera.github.io/app-unexpected-keyboard-layout-editor/
=> Update Custom-layouts.md reference to web editor

res/values/arrays.xml, res/values/strings.xml, res/xml/settings.xml, srcs/juloo.keyboard2/Config.java, srcs/juloo.keyboard2/Pointers.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/1059
The first commit adds an option for changing the speed at which the cursor moves when sliding on the space bar. The next commits fix a bug and make the slider slightly easier to use.
=> Slider sensitivity option and improve slider ergonimics

res/values/arrays.xml, res/values/strings.xml, res/values/themes.xml, srcs/juloo.keyboard2/Config.java
It was originally a black theme. I added color to it.
=> Cobalt & Pine theme
