- srcs/juloo.keyboard2/KeyValue.java
`srcs/juloo.keyboard2/KeyValue.java` was updated to replace `Conf` with
`⛭` (`\u2699`) and `:)` with `☻` (`\u263B`).
> Use symbols for configuration and emoji keys

- res/values/arrays.xml
- res/xml/method.xml
- res/xml/qwerty_lv.xml
- srcs/juloo.keyboard2/Config.java
A customised Latvian specific QWERTY layout (QWERTY (Latvian)) was added to access all Latvian diacritic characters with a swipe.
Additionally caron, cedille and macron accents were enabled for this layout.
This is what I had in mind when I started working on #27 - to access Latvian diacritic characters with a swipe. I figured out that adding a new and customised Latvian specific QWERTY layout would be the best approach because if everybody who would like to access language specific characters with a swipe added those to the QWERTY layout, all key slots soon would be filled.
Is this acceptable/not against the idea or vision behind this keyboard application?
This pull request depends on #27 because of the new accents - caron and macron.
> Add Latvian specific QWERTY layout

- res/xml/method.xml
Add support to show accents for the Portuguese language
The accents used are:
aigu(agudo), cedille, circonflexe, grave(crase) and tilde
> Add support to show accents for Portuguese language

- Makefile
Fix #55.
Pass full path when calling `apksigner` (using the variable `$(ANDROID_BUILD_TOOLS)`).
> Makefile: Pass full path when calling apksigner

- res/xml/azerty.xml
- res/xml/numeric.xml
- res/xml/qwerty.xml
- res/xml/qwerty_lv.xml
- res/xml/qwertz.xml
- srcs/juloo.keyboard2/Keyboard2View.java
- srcs/juloo.keyboard2/KeyboardData.java
- srcs/juloo.keyboard2/Theme.java
Fix/implement #56.
Add a new boolean parameter "edgekeys" for defining keys that have the additional (swipe) keys on the edges (top, right, left, bottom) instead of at the corners (top left, top right, bottom left, bottom right).
Example:
```xml
<key width="1.2" key1="up" key2="right" key3="left" key4="down" edgekeys="true"/>
```
If the `edgekeys` parameter is omitted, it defaults to `false` (swipe diagonally for additional keys).
This pull request also changes the arrow keys in all layouts to the alternative edge style:
Before:
After:
> Allow edge keys instead of corner keys (swipe vertically/horizontally)

- srcs/juloo.keyboard2/KeyValue.java
> Replace unusual return symbol

- res/xml/numeric.xml
- srcs/juloo.keyboard2/KeyModifier.java
- srcs/juloo.keyboard2/KeyValue.java
Add a way to input ordinal markers, using the accent system inside the numeric keypad.
So we can type 1ª (primeira) , 2º (segundo) , 1ˢᵗ , 2ⁿᵈ , 3ʳᵈ, 20ᵗʰ, 50ʳᵉ, 60ᵈᵉʳ
(note that especially the ª º are NOT superscript 'a o'. they are specific symbols for ordinals)
The other letters can be combined for a broad range of different languages ᵉ ᵉʳᵈ ᵈᵉʳ ʳᵉ ˢᵗ ʳᵉˢ ᵈᵉʳˢ ᵉˢ ᵈˢ ⁿᵈ ʳᵈ ᵗʰ
> add-ordinal-numbers-symbol-system

- res/xml/numeric.xml
The colon symbol : is used together with numbers really all the time, it should be available in the numeric keypad
> add colon symbol to numeric keyboard

- res/xml/qwerty_lv.xml
`res/xml/qwerty_lv.xml` was updated to add the missing full stop character (`.`) as it got lost when the bottom row was moved to a separate XML `res/xml/bottom_row.xml` as it was placed on the arrows key.
Additionally `?` was relocated, giving its place to the full stop.
> Add a missing full stop to Latvian QWERTY layout

- .github/workflows/make-apk.yml
- .gitignore
- CONTRIBUTING.md
- Makefile
I got in this rabbit hole, and spent my night without sleeping, but I ended with a working CI flow, which utilizes caches and runs in 40sec after the first cache is done.
The steps are simplified, and there is no dirty OS upgrade anymore in order to get a newer version of FontForge. The new FontForge is self-contained and has no dependency.
Only doubt I have is if its a good thing to cache the whole folder /usr/local/bin, but it's working well so far.
> Upgrade CI workflow

- res/xml/numeric.xml
- res/xml/settings.xml
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/KeyModifier.java
- srcs/juloo.keyboard2/KeyValue.java
I liked the streamlining of the symbols with FN keys from PR #112,
but I disliked the arrows taking room on all keys on the numeric keyboard. Some of that conflicting with some of my layouts.
So I cherry picked @ArenaL5 commits from his PR, and worked on top of it. Instead of allocating the arrows directly to the keyboard on all keys, I created a Single key for Arrows, using the accent system, and once I was doing that, I also created one for Box frames. Both Arrows and Box can have variations if paired with Shift or Alt in the Box case. The Box key can also be configurable to be Lockable.
> `Arrows` and `Box` system

- srcs/juloo.keyboard2/Keyboard2View.java
- srcs/juloo.keyboard2/KeyboardData.java
- srcs/juloo.keyboard2/Pointers.java
I have seen a [Google Play review (in Portuguese)](https://play.google.com/store/apps/details?id=juloo.keyboard2&hl=pt_BR&gl=US&reviewId=gp%3AAOqpTOEjFVJva0Z97IWxFpGxBGCbGh3Dzpo4BGEqO0xC0v5uJTtZGegDXELaXkt7NbwBjQ8hQ9GZH-OV0OAw4g) suggesting (among others) that 0 could be recognized with an up swipe, regardless of the direction (since the 0 has a different direction from the other numbers, probably).
So I decided to solve this by always choosing the closest key to the swipe direction. So instead of computing the index of the key in `onTouchMove`, I compute the direction of the swipe (from 1 to 8, 0 is no swipe) and I replaced `Key.getValue` by `Key.getAtDirection`, which finds the closest key and handles `edgekeys`. Now `Pointer` keeps track of `selected_value` instead of `value_index`.
> Select the closest key on swipe

- res/xml/local_ru_jcuken.xml
The 'ъ' key is rarely used, and therefore we may move it to 'ь', as usual, and then increase the width of the keys.
> Move 'ъ' where it belongs and increase the width of the keys

- res/values-fr/strings.xml
- res/values/arrays.xml
- res/values/strings.xml
- res/values/themes.xml
- srcs/juloo.keyboard2/Config.java
Hi, just discovered this keyboard on my android ereader (color eink Boox Nova Air C), and blindly edited a theme that would be least artifacty on the eink screen. Based on the Light one.
That's just an untested idea (browser-edited with a typo in the commit message ;) ). I simply would be glad if anything eink-oriented landed in a future release :)
> Add white e-ink oriented theme

- metadata/android/cs-CZ/full_description.txt
- metadata/android/cs-CZ/short_description.txt
- metadata/android/cs-CZ/title.txt
- res/values-cs/strings.xml
- res/xml/method.xml
- res/xml/qwertz_cs.xml
- srcs/juloo.keyboard2/Config.java
Translated keyboard and created Czech multilingual "practical" layout for faster typing and typing in commonly used languages (German, Slovak + French w/accents)
_I've designed the layout to be more useful and practical in typing while preserving QWERTZ and certain alphanumeric symbols (PC keyboard) where change wasn't needed/available_
I've tested it (and made changes) for a week. I plan on using it for a long time so feel free to modify or ask for help or changing commits.
_Thank you for this amazing gift of a keyboard to us all. Hope you're doing well._
> Added Czech translation and layout

- .github/workflows/make-apk.yml
Add details to the name of the artifact, to distiguish downloads of it between multiple branches while testing
for example:
the resulting zip file will look like this:
the unique name for each branch helps a lot while testing/debuging diferent versions
> Rename resulting CI artifact

- res/values-cs/strings.xml
- res/values-de/strings.xml
- res/values-es/strings.xml
- res/values-fr/strings.xml
- res/values-it/strings.xml
- res/values-ko/strings.xml
- res/values-lv/strings.xml
- res/values-pl/strings.xml
- res/values-pt/strings.xml
- res/values-ru/strings.xml
- res/values-tr/strings.xml
- res/values-zh-rCN/strings.xml
- res/values/strings.xml
- res/xml/settings.xml
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/Keyboard2View.java
Quite missed this feature from the other keyboard I used in the past along with remote desktop viewers and emulators, so I decided to add it here. This setting is split into 3 options.
This are a few examples what it looks like with the following values:
background opacity: 70%
key opacity: 30%
key pressed opacity: 30%
Settings screen:
Remote desktop app:
> Make the keyboard transparent

- res/values/arrays.xml
- res/xml/ar_alt.xml
- res/xml/ar_pc.xml
- res/xml/method.xml
- srcs/juloo.keyboard2/Config.java
This request is to add Arabic Keyboard
The layout follows closely IBM PC (https://en.wikipedia.org/wiki/Arabic_keyboard#IBM_PC_Arabic_Keyboard) 
Only alteration is the letter (ذ) usually in the number row was moved to the end of the first row. This layout is the most common from my experience.
The following are a screenshots of the current layout, suggestions are welcome.
Without number row:
With number row:
> Add Arabic layout

- srcs/juloo.keyboard2/Pointers.java
This unconditionally removes all pointers (touches) pressing modifiers which are not already locked, avoiding that the (currently) latched modifier will be locked aventually.
This can be verfified while sliding the space bar to move the cursor left or right.
Closes #319.
> Do not lock modifiers if sliding a key

- sync_translations.py
When running sync_translations.py on Windows, an error will show because it use gbk encoding by default. Using utf-8 encoding explicitly can fix it.
> Explicitly use utf-8 encoding while formatting translations on Windows.

- res/xml/latn_azerty_fr.xml
- res/xml/latn_qwerty_br.xml
- res/xml/latn_qwerty_es.xml
- res/xml/latn_qwerty_hu.xml
- res/xml/latn_qwerty_lv.xml
- res/xml/latn_qwerty_no.xml
- res/xml/latn_qwerty_pl.xml
- res/xml/latn_qwerty_ro.xml
- res/xml/latn_qwerty_se.xml
- res/xml/latn_qwerty_tr.xml
- res/xml/latn_qwerty_us.xml
- res/xml/latn_qwerty_vi.xml
- res/xml/latn_qwertz.xml
- res/xml/latn_qwertz_cz.xml
- res/xml/latn_qwertz_cz_multifunctional.xml
- res/xml/latn_qwertz_de.xml
- res/xml/latn_qwertz_hu.xml
- res/xml/latn_qwertz_sk.xml
- srcs/juloo.keyboard2/ExtraKeysPreference.java
- srcs/juloo.keyboard2/KeyModifier.java
I use the QWERTY (US) layout and I miss these punctuation marks, which can be found in other Android keyboards including the LineageOS stock keyboard US layout. So I added section mark and dagger as user-selectable extras on the S and X keys (except for the layouts that already had the section mark). Double dagger can be entered as a modified dagger.
> Add dagger, double dagger, section mark, and pilcrow as extra keys on QWERTY-like layouts

- res/xml/greekmath.xml
Uppercase koppa can still be entered as shift+koppa.
> Change Greek math koppa to lowercase

- res/xml/latn_neo2.xml
The update to the bottom row did not get into neo2. This resolves the warnings found by check_layout.py:
- Replace "-" with "—" on the "ß" key
"-" should be U+2011 (non-breaking hyphen), but this mostly is not recognized by apps, —" (U+2014, EM Dash) is in the second layer of the same key and was not available before.
- ~"$" and "€" are available again ("$" is not available from the additional key menu, is this intentional)~
edit: $ was already present, I reverted this point
- Update bottom row special keys
https://github.com/Julow/Unexpected-Keyboard/blob/5b4345088d419ab2b26df11fbc80bc265181df93/check_layout.output#L65-L68
> Resolve layout warnings in neo2

- res/values-cs/strings.xml
Response to usual string updates
> Update strings.xml (cz_CS)

- AndroidManifest.xml
To detect voice IMEs, Unexpected Keyboard calls `InputMethodManager.getEnabledInputMethodList`
https://github.com/Julow/Unexpected-Keyboard/blob/95bd9312a7714e1fbee2a792a12d2b9ced36b708/srcs/juloo.keyboard2/VoiceImeSwitcher.java#L108
Internally, this method eventually calls a method that returns a [filtered list of packages](https://developer.android.com/training/package-visibility) that may not include the installed voice IME, and thus Unexpected Keyboard unexpectedly claims no voice input is installed because it can't see it.
The fix is to explicitly state in the manifest that we want to query for other IMEs, based on https://developer.android.com/training/package-visibility/declaring
This is not an issue with Google's voice input or other preinstalled voice inputs because they usually …
> Add `<queries>` element in AndroidManifest to fix voice IME detection in modern Android

- .github/workflows/check-layouts.yml
- .github/workflows/check-translations.yml
- .github/workflows/make-apk.yml
node.js v16 is end-of-life and github actions needed an update to node.js v20
> Update CI to node.js-20

- srcs/layouts/latn_neo2.xml
Update bottom row in neo2 layout to match default and added new keys.
Resolves layout warnings.
> neo2: Update bottom row

- CONTRIBUTING.md
- build.gradle
- srcs/layouts/LICENSE
- srcs/layouts/latn_neo2.xml
- srcs/layouts/latn_qwertz.xml
Layout definitions are licensed differently from the rest of the application source code to allow use in other projects related or unrelated to Unexpected Keyboard.
Layout authors can ask to add an exception for the layout they authored. I'm not asking for everyone to answer and I reserve the right to relicense individual layouts back to GPLv3 in the future.
Note: I moved the layout definitions into the directory `srcs/layouts` in ad7314a as a general improvement and to make this change easier.
cc Interested users @Lixquid
cc Layout authors @rafasaurus @lyubomirv @Shareef101 @ElucGeek @shmVirus @GoRaN909 @mostafaayesh @lrvideckis @K4zoku @Raj9039852537 @lpv11 @iamrasel @RamKromberg @Validbit @Dimethylebutane @thabubble @eandersons @nanno @quantenzitrone @erqan @igorSilCar @carrot-cookie …
> Relicense layout definitions under CC0

- check_layout.output
- res/values/layouts.xml
- srcs/juloo.keyboard2/KeyModifier.java
- srcs/layouts/guj_phonetic_in.xml
Added Gujarati phonetic layout.
Tested debug APK build(gradle and java), working fine on my device.
> Gujarati phonetic layout

- res/raw/emojis.txt
> Update to Unicode Emoji v15.1

- check_layout.output
- res/values/layouts.xml
- srcs/layouts/shaw_imperial_en.xml
I see that there are no options for typing in shavian on android besides the keyman app. It is okay, but somewhat slow and it's not great switching back and forth between keyboard apps all the time. After I learned that one can add a custom layout to Unexpected keyboard, I immediately thought about finally unifying all my layouts in one app, so i don't have to switch all the time.
Hope it will be useful for somebody.
And thanks for this great project!
> Add Shaw Imperial layout

- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/KeyEventHandler.java
- srcs/juloo.keyboard2/KeyValue.java
- srcs/juloo.keyboard2/Pointers.java
Might fix https://github.com/Julow/Unexpected-Keyboard/issues/566
The two visible changes are:
- The spacebar slider sensitivity no longer depend on the "Swiping distance" option. This made the cursor harder to control when the option was not set to "Normal". Might be related: https://github.com/Julow/Unexpected-Keyboard/issues/548
- The spacebar sensitivity increases when the finger travels faster. This hopefully increases the range without reducing the precision on short movements.
> Move the cursor further when sliding faster on the spacebar

- CONTRIBUTING.md
Hi there!
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
> Update NixOS wiki link

- srcs/juloo.keyboard2/Gesture.java
- srcs/juloo.keyboard2/KeyModifier.java
- srcs/juloo.keyboard2/KeyValue.java
- srcs/juloo.keyboard2/Pointers.java
This implements clockwise/anticlockwise circle and round trip gestures inspired by Messagease.
The circle gestures start after a small threshold to avoid making the regular swipe too hard to aim.
The gestures do:
- clockwise circle: Shift variant of the center symbol
- anticlockwise circle: Fn variant of the center symbol
- round trip: Fn variant of the targetted side symbol
> Circle and round trip gestures

- srcs/juloo.keyboard2/Keyboard2View.java
Take display cutouts and navigation bars into account when computing the keyboard width on SDK >= 30.
> Fix overflow due to navigation on the right and cutouts

- res/values-es/strings.xml
Using clipboard → portapapeles
Using gesture → gesto
If Android uses different terms, it's preferable to align with those
> New Spanish translations

- check_layout.output
- res/values/layouts.xml
- srcs/layouts/cyrl_lynyertz_sr.xml
Adds Serbian Cyrillic layout. Modmap of Fn key allows for desktop-like easier access to actions such as selectAll, copy, paste, etc. This is because, unlike desktop systems, on mobile ctrl does not combine with cyrillic keys to perform actions.
> Add Serbian Cyrillic layout

- check_layout.output
- res/values/layouts.xml
- srcs/layouts/latn_qwerty_sr.xml
Adds Serbian Latin QWERTY layout. Serbian language uses both Latin and Cyrillic as its official scripts, and this variant should cover anyone from Serbo-Croatian speaking group that uses Latin script.
> Add Serbian Latin QWERTY layout

- doc/Custom-layouts.md
Put new example in Examples section; put all overview material at start; use "modmap" for the modmap tag but "mapping" for the various subtags; set out each subtag separately; stop illustrating example mappings as complete modmap.
> Modmap: Reorganize

- check_layout.output
- shell.nix
- srcs/layouts/latn_bone.xml
- fix jdk version in gradle issue with `shell.nix`
- fix alignment with tabs mess in bone layout file
- make like actual bone layout, instead of trying to fit it into a 10 key
wide keyboard
- fixes missing `ü` `ä` `ö`
- fix missing `$`
- moves `q` and `ß` where they belong
- remove all the diacritic keys (they can be added through the
settings as extra keys)
- kept the number row extra keys integration into top row
- kept the idea of compressing `,` and `.` into the swipe actions of the
bottom row
- kept the number keys as `key4` in the layer 4 positions (instead of
moving them to a number row, which I also considered)
closes #741
> fix bone layout

- res/xml/settings.xml
- srcs/juloo.keyboard2/Config.java
PR as per #744
This particular implementation increases default label size by 15%, while existing user set preferences remain unaffected. However, upon testing various default values (1.4, 1.3, 1.25, 1.2, 1.15, 1.1) against different keyboard heights (ranging 27%-35% for portrait mode), I came to the conclusion this might not be the right approach to resolve the issue raised there.
Why? Because the reason I believe we were increasing label size is because we were also reducing the height of the keyboard. With default keyboard height of 35%, label size of 1 is just fine. Only as we reduce the height, label becomes smaller and less intelligible.
However, modification to how the label size scales with regard to keyboard height would require a different approach, with more testing...
> Increase default label size

- build.gradle
- doc/Possible-key-values.md
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/KeyEventHandler.java
- srcs/juloo.keyboard2/KeyValue.java
- srcs/juloo.keyboard2/KeyValueParser.java
- srcs/juloo.keyboard2/prefs/CustomExtraKeysPreference.java
- test/juloo.keyboard2/KeyValueParserTest.java
- test/juloo.keyboard2/KeyValueTest.java
This allows to add new kinds of keys that need more data without making KeyValue's footprint bigger for common keys.
This changes the [_symbol] field into [_payload], which holds the same as the previous field for more common keys but can hold bigger objects for keys of the new "Complex" kind.
This also adds a complex key: String keys with a symbol different than the outputted string.
Unit tests are added as the Java language is not helpful in making robust code.
> Add complex keys

- check_layout.output
- res/values/layouts.xml
- srcs/layouts/latn_qwertz_sq.xml
Is this all that's needed to add a new layout?
> Albanian QWERTZ layout

- check_layout.output
- res/values/layouts.xml
- srcs/layouts/latn_qwertz_cz_diacritics.xml
Layout similar to https://f-droid.org/en/packages/cz.vitSkalicky.klavesnice/ or iPhone Czech keyboard
> Czech diacritic QWERTZ layout

- srcs/layouts/grek_qwerty.xml
Added Greek accent symbol button; a necessary key that should always be on the keyboard, as every word over 2 syllables contains one
> Added Greek accent symbol button

- AndroidManifest.xml
- res/layout/launcher_activity.xml
- res/values/styles.xml
- res/values/values.xml
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/Keyboard2.java
- srcs/juloo.keyboard2/Keyboard2View.java
- srcs/juloo.keyboard2/LauncherActivity.java
- srcs/juloo.keyboard2/Utils.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/842
The keyboard background now extends under the system bars and display cutout but the keys do not.
This does not yet handle the gesture navigation bar changing height when the IME dismiss and switch buttons are added.
> Proper support for Android 15 edge-to-edge

- res/xml/number_row.xml
From #890; a potential question would be whether to put `()` on the same char on different directions, or keep separately on 9/0; both are done by some layouts.
> Add swipe actions on number bar

- srcs/layouts/deva_alt.xml
- remove keypad key in favor of circular swipes. This allows a larger backspace key
- move around some symbols in a way which I've found more convenient:
- ऽ key is now a tap because i use it frequently
- ् key moved to center to be convenient to tap with both thumbs as i use this frequently
- । key is now a swipe (previously it was a tap); i use this symbol very seldom
> misc changes to deva alt layout

- doc/Possible-key-values.md
- srcs/juloo.keyboard2/Autocapitalisation.java
- srcs/juloo.keyboard2/KeyEventHandler.java
- srcs/juloo.keyboard2/KeyValue.java
- srcs/juloo.keyboard2/KeyValueParser.java
- srcs/juloo.keyboard2/prefs/CustomExtraKeysPreference.java
- test/juloo.keyboard2/KeyValueParserTest.java
Add "macro" keys that behave as if a sequence of keys is typed.
Macro can be added to custom layouts or through the "Add keys to the keyboard option" using the following syntax:
V:ctrl,v
CA:ctrl,a,ctrl,c
<<:ctrl,backspace
> Macro keys

- doc/Possible-key-values.md
Other queries:
- In your example of a key that sends an email address, `@` isn't quoted at all. If items in the first table aren't mandatory, the doc should say so, or remove the items altogether.
- Possible helpful sentence: "If you revise a custom layout but Unexpected Keyboard gives a pop-up reporting a syntax error, look for characters you added that could be escaped."
> doc: Massage section on "Escape codes"

- srcs/juloo.keyboard2/Autocapitalisation.java
- srcs/juloo.keyboard2/KeyEventHandler.java
- srcs/juloo.keyboard2/Keyboard2.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/915
Add a delay before sending the next key to avoid race conditions causing
keys to be handled in the wrong order. Notably, KeyEvent keys handling
is scheduled differently than the other edit functions.
> Add a delay after a Keyevent key in a macro 

- srcs/layouts/latn_colemak.xml
I swapped the placement of ! and | on the Colemak layout to make it more reasonable. It makes more sense to group | with the slashes since it's usually grouped with \ on a physical keyboard, and it makes more sense to have ! next to ? as they are both punctuation marks.
> Swapping the default placement of ! and | on the Colemak layout.

- doc/Possible-key-values.md
The non-backward-compatible change to the XML should be mentioned as users must revise their layouts.
> Possible-key-values.md—Note syntax change for slider

- srcs/layouts/latn_qwerty_jp.xml
Even though a Latin-script keyboard is borderline useless for Japanese, which uses kanji, hiragana, and katakana, I’ve added a dead key for the macron, used in rōmaji transcription for long vowels.
> Add macron dead key to QWERTY (Japanese)

- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- res/values-cs/strings.xml
- res/values-de/strings.xml
- res/values-es/strings.xml
- res/values-fa/strings.xml
- res/values-fr/strings.xml
- res/values-it/strings.xml
- res/values-ja/strings.xml
- res/values-ko/strings.xml
- res/values-lv/strings.xml
- res/values-pl/strings.xml
- res/values-pt/strings.xml
- res/values-ro/strings.xml
- res/values-ru/strings.xml
- res/values-tr/strings.xml
- res/values-uk/strings.xml
- res/values-vi/strings.xml
- res/values-zh-rCN/strings.xml
- res/values/strings.xml
- res/xml/settings.xml
- shell.nix
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/FoldStateTracker.java
- srcs/juloo.keyboard2/Keyboard2.java
- srcs/juloo.keyboard2/SettingsActivity.java
PR adds separate layouts and separate layout settings for folded and unfolded state of the device.
Unfortunately, the only way to get fold state at the moment is through AndroidX WindowManager. Native Android APIs are internal. So I had to update some dependencies, raise java version and raise compile SDK to include AndroidX in the project.
this fixes #754
> Better support for foldable devices

- doc/Custom-layouts.md
- srcs/juloo.keyboard2/KeyboardData.java
- srcs/layouts/cyrl_jcuken_ru.xml
- srcs/layouts/cyrl_yqukeng_tj.xml
- srcs/layouts/cyrl_yxukeng_os.xml
- srcs/layouts/deva_alt.xml
- srcs/layouts/hebr_1_il.xml
- srcs/layouts/latn_bepo_fr.xml
Scale the width of the keys in the row to match a value. Useful to remove space on the right of the row without adding a 'width' attribute to each key.
Builtin layouts are changed to use the new attribute.
> Add <row scale=""> attribute

- srcs/juloo.keyboard2/KeyEventHandler.java
- srcs/juloo.keyboard2/Pointers.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/954 replace https://github.com/Julow/Unexpected-Keyboard/pull/1012
Emptying the selection with the spacebar slider puts the selection mode in an unexpected state. This checks that this doesn't happen.
The selection ends can now cross each other, reversing the selection order. Special care is made to make sure that the sliders go in the expected direction.
Pointers is changed to send a `onPointerDown` for the first slider event instead of a `onPointerHold`. This event is detected in `KeyEventHandler` and the selection ends are reordered if needed when sliding again.
> Improve selection mode when selection ends cross

- srcs/juloo.keyboard2/Keyboard2.java
- srcs/juloo.keyboard2/Keyboard2View.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/946, https://github.com/Julow/Unexpected-Keyboard/issues/993, https://github.com/Julow/Unexpected-Keyboard/issues/1006 and https://github.com/Julow/Unexpected-Keyboard/issues/1017
This fixes the unwanted bottom margin appearing on OneUI 7 and perhaps other Android 15 based systems.
> Fix unwanted bottom margin on Samsung OneUI 7 

- res/values/values.xml
- srcs/juloo.keyboard2/Config.java
- srcs/juloo.keyboard2/Keyboard2View.java
- srcs/juloo.keyboard2/Utils.java
Fix the extra space that was appearing when the gesture-navigation bar didn't contain the "switch IME" or "close IME" buttons.
This was found on OneUI 7 with the two "keyboard key" related options turned off.
> Fix extra bottom margin when navbar buttons absent

- srcs/juloo.keyboard2/Keyboard2View.java
Fix https://github.com/Julow/Unexpected-Keyboard/issues/1038
The label size was computed against the width of keys on the keyboard, which resulted in a different label size on different layouts. Notably, it made the labels very small on a 11 columns layout and relatively larger on the numpad.
The label size is now computed against a baseline of 1/10 of the width of the screen.
> Fix very small label size on 11+ columns layouts

- build.gradle
- sync_translations.py
The diffs created by sync_translations.py creates conflicts with the changes made on Weblate. It is disable to make merging translations from Weblate easier.
> gradle: Disable sync_translations

- res/values/arrays.xml
- res/values/strings.xml
- res/values/themes.xml
- srcs/juloo.keyboard2/Config.java
Why this theme specifically?
Because it is a soothing light theme available on the helix editor.
For Light mode editing having both editor and keyboard on the same thing makes ux more soothing.
> add Everforest Light theme

- doc/Custom-layouts.md
- srcs/juloo.keyboard2/KeyModifier.java
Alternative fix for https://github.com/Julow/Unexpected-Keyboard/issues/1082
This allows assigning mappings to letters without changing the Shift mappings and making uppercase impossible to type.
For gestures, the Shift modifier is still applied first, unless a custom mapping for <fn/> is set for the key.
> Use the `<fn />` mappings first when typing a gesture

- check_layout.py
- gen_layouts.py
- res/values/layouts.xml
Whilst I was trying to add a keyboard layout I encountered issues with the python scripts used to generate the layout lists.
On my setup the open() and xml.elementtree(),write() defaulted to using CP1252, explicitly stating the encoding as UTF-8 in the scripts fixed this.
> Python script encoding fix
